/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#00236f',
        'on-primary': '#ffffff',
        'primary-container': '#1e3a8a',
        'on-primary-container': '#90a8ff',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b6c4ff',
        'inverse-primary': '#b6c4ff',
        'on-primary-fixed': '#00164e',
        'on-primary-fixed-variant': '#264191',

        'secondary': '#904d00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe932c',
        'on-secondary-container': '#663500',
        'secondary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#ffb77d',
        'on-secondary-fixed': '#2f1500',
        'on-secondary-fixed-variant': '#6e3900',

        'tertiary': '#4b1c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6e2c00',
        'on-tertiary-container': '#f39461',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb691',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#773205',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'background': '#f8f9ff',
        'on-background': '#0b1c30',
        'surface': '#f8f9ff',
        'on-surface': '#0b1c30',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#444651',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',

        'outline': '#757682',
        'outline-variant': '#c5c5d3',
        'surface-tint': '#4059aa',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'h1-display': ['Inter', 'sans-serif'],
        'h2-headline': ['Inter', 'sans-serif'],
        'h3-title': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'table-header': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'h1-display': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2-headline': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'h3-title': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'table-header': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'gutter': '1.5rem',
        'card-padding': '1.25rem',
        'container-padding': '2rem',
        'stack-gap': '1rem',
        'sidebar-width': '260px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(2, 8, 23, 0.06), 0 1px 3px rgba(2, 8, 23, 0.06)',
      },
    },
  },
  plugins: [],
}
